name: base_project2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.8.4
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0
  cached_network_image: ^3.2.3

  # State Management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.0

  # Routing
  go_router: ^10.1.2

  # Network
  dio: ^5.3.3
  retrofit: ^4.0.3
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1
  dio_http_formatter: ^3.1.0

  # Storage
  flutter_secure_storage: ^8.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Security
  encrypt: ^5.0.3
  local_auth: ^2.1.6
  flutter_jailbreak_detection: ^1.10.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3

  # Utils
  dartz: ^0.10.1
  logger: ^1.4.0
  intl: ^0.18.1
  uuid: ^3.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0

  # Analytics & Monitoring
  sentry_flutter: ^7.10.1
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  firebase_remote_config: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^2.0.3
  dart_code_metrics: ^5.7.6

  # Code Generation
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  freezed: ^2.4.5
  isar_generator: ^3.1.0+1

  # Testing
  mocktail: ^1.0.1
  bloc_test: ^9.1.4
  golden_toolkit: ^0.15.0

  # CI/CD
  flutter_flavorizr: ^2.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
